<?php

return [
    'AED' => 'AED - United Arab Emirates Dirham',
    'USD' => 'USD - United States Dollar',
    'EUR' => 'EUR - Euro',
    'GBP' => 'GBP - British Pound Sterling',
    'SAR' => 'SAR - Saudi Riyal',
    'QAR' => 'QAR - Qatari Riyal',
    'OMR' => 'OMR - Omani Rial',
    'KWD' => 'KWD - Kuwaiti Dinar',
    'BHD' => 'BHD - Bahraini Dinar',
    'INR' => 'INR - Indian Rupee',
    'PKR' => 'PKR - Pakistani Rupee',
    'EGP' => 'EGP - Egyptian Pound',
    'JPY' => 'JPY - Japanese Yen',
    'CNY' => 'CNY - Chinese Yuan',
    'AUD' => 'AUD - Australian Dollar',
    'CAD' => 'CAD - Canadian Dollar',
    'CHF' => 'CHF - Swiss Franc',
    'SEK' => 'SEK - Swedish Krona',
    'NOK' => 'NOK - Norwegian Krone',
    'DKK' => 'DKK - Danish Krone',
    'SGD' => 'SGD - Singapore Dollar',
    'HKD' => 'HKD - Hong Kong Dollar',
    'NZD' => 'NZD - New Zealand Dollar',
    'ZAR' => 'ZAR - South African Rand',
    'TRY' => 'TRY - Turkish Lira',
    'RUB' => 'RUB - Russian Ruble',
    'BRL' => 'BRL - Brazilian Real',
    'MXN' => 'MXN - Mexican Peso',
    'KRW' => 'KRW - South Korean Won',
    'THB' => 'THB - Thai Baht',
    'MYR' => 'MYR - Malaysian Ringgit',
    'IDR' => 'IDR - Indonesian Rupiah',
    'PHP' => 'PHP - Philippine Peso',
    'VND' => 'VND - Vietnamese Dong',
];
