<?php

return [
    'English',
    'Arabic',
    'Hindi',
    'Urdu',
    'French',
    'Spanish',
    'German',
    'Italian',
    'Portuguese',
    'Russian',
    'Chinese (Mandarin)',
    'Chinese (Cantonese)',
    'Japanese',
    'Korean',
    'Turkish',
    'Persian (Farsi)',
    'Bengali',
    'Punjabi',
    'Tamil',
    'Telugu',
    'Marathi',
    'Gujarati',
    'Malayalam',
    'Kannada',
    'Thai',
    'Vietnamese',
    'Indonesian',
    'Malay',
    'Tagalog (Filipino)',
    'Dutch',
    'Polish',
    'Swedish',
    'Danish',
    'Norwegian',
    'Finnish',
    'Greek',
    'Hebrew',
    'Czech',
    'Hungarian',
    'Romanian',
    'Ukrainian',
    'Swahili',
    'Afrikaans',
];
